apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
  namespace: udaconnect
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  PERSONS_GRPC_URL: "udaconnect-persons-grpc.udaconnect.svc.cluster.local:30003"
  KAFKA_URL: "kafka-release.default.svc.cluster.local:9092"
  KAFKA_TOPIC: "location"