kubectl delete -f deployment/application-configmap.yaml
kubectl delete -f deployment/db-secret.yaml
kubectl delete -f deployment/postgres.yaml
kubectl delete -f deployment/udaconnect-connection.yaml
kubectl delete -f deployment/udaconnect-frontend.yaml
kubectl delete -f deployment/udaconnect-location-consumer.yaml
kubectl delete -f deployment/udaconnect-location-producer.yaml
kubectl delete -f deployment/udaconnect-persons-grpc.yaml
kubectl delete -f deployment/udaconnect-persons-rest.yaml