apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connection
  name: udaconnect-connection
  namespace: udaconnect
spec:
  ports:
  - name: "connection-api-port"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: udaconnect-connection
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connection
  name: udaconnect-connection
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connection
  template:
    metadata:
      labels:
        service: udaconnect-connection
    spec:
      containers:
      - image: hemanthkandukuri/connections_api_rest:v1.0.0
        name: udaconnect-connections-api-rest
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: PERSONS_GRPC_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: PERSONS_GRPC_URL
      restartPolicy: Always
