apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-consumer
  name: udaconnect-location-consumer
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-consumer
  template:
    metadata:
      labels:
        service: udaconnect-location-consumer
    spec:
      containers:
      - image: hemanthkandukuri/location_kafka_consumer:v1.0.0
        name: udaconnect-location_kafka_consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: PERSONS_GRPC_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: PERSONS_GRPC_URL
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC
      restartPolicy: Always
