## MOVE THIS FILE to `.github/workflows/docker-build.yaml` TO EXECUTE IT

# This is a basic workflow to help you get started with Actions

name: Udaconnect - Package with Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_connection_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_UDACITY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/connections_api_rest/
          file: ./modules/connections_api_rest/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hemanthkandukuri/connections_api_rest:v1.0.0
  build_forntend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_UDACITY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/frontend/
          file: ./modules/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hemanthkandukuri/frontend:v1.0.0
  build_location_kafka_consumer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_UDACITY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/location_kafka_consumer/
          file: ./modules/location_kafka_consumer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hemanthkandukuri/location_kafka_consumer:v1.0.0
  build_location_kafka_producer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_UDACITY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/location_kafka_producer/
          file: ./modules/location_kafka_producer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hemanthkandukuri/location_kafka_producer:v1.0.0
  build_persons_api_grpc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_UDACITY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/persons_api_grpc/
          file: ./modules/persons_api_grpc/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hemanthkandukuri/persons_api_grpc:v1.0.0
  build_persons_api_rest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_UDACITY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/persons_api_rest/
          file: ./modules/persons_api_rest/Dockerfile
          platforms: linux/amd64
          push: true
          tags: hemanthkandukuri/persons_api_rest:v1.0.0
          
